name: release

on:
  push:
    tags:
      - 'v1.*.*'

env:
  GO111MODULE: on
  sha_short_length: 8
  release_version: ${{ github.ref_name }}


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.22

      - uses: actions/checkout@v2

      - name: Get Short SHA
        id: short_sha
        run: echo "GIT_SHORT_SHA=$(git rev-parse --short=${{ env.sha_short_length }} HEAD)" >> $GITHUB_ENV

      # - name: Run Tests
      #   run: go test -v ./...

      - name: Build
        run: |
          go build \
          -ldflags "-X container-test-cli/internal/version.Version=${{ env.release_version }}-$GIT_SHORT_SHA" \
          -o container-test-cli ./cmd/container-test-cli/main.go

      - name: Create Release Binary
        id: create_release_binary
        run: |
          BINARY_NAME=container-test-$(go env GOOS)-$(go env GOARCH)
          mv container-test-cli $BINARY_NAME
          echo "binary_name=$BINARY_NAME" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.release_version }}
          release_name: Release ${{ env.release_version }}
          draft: false
          prerelease: true

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.create_release_binary.outputs.binary_name }}
          asset_name: ${{ steps.create_release_binary.outputs.binary_name }}
          asset_content_type: application/vnd.github.v3+json
